
export const LOAD_GENRE_LIST = 'LandingPage/LOAD_GENRE_LIST'
export const LOAD_GENRE_LIST_INITIATED = 'LandingPage/LOAD_GENRE_LIST_INITIATED'
export const LOAD_GENRE_LIST_SUCCESS = 'LandingPage/LOAD_GENRE_LIST_SUCCESS'
export const LOAD_GENRE_LIST_FAILED = 'LandingPage/LOAD_GENRE_LIST_FAILED'


export const MOVIE_LOADING_INITIATED = 'LandingPage/MOVIE_LOADING_INITIATED'
export const MOVIE_LOADING_SUCCESS = 'LandingPage/MOVIE_LOADING_SUCCESS'
export const MOVIE_LOADING_FAILED = 'LandingPage/MOVIE_LOADING_FAILED'
